site_name: Receitalista
repo_url: https://github.com/mdsreq-fga-unb/2022.2-Receitalista

theme:
    name: material
    language: pt
    features:
        - navigation.tabs
    # logo: ./assets/GDS.png
    # favicon: ./assets/GDS.png
    palette:
        primary: brown
        accent: cyan
        
nav:
  - Home: home/index.md
  - Documentação: 
    - Visão do produto e projeto: documentacao/visao-produto.md
  - Entregas: entregas/entregas.md